name: TechNight-WebApp-CICD

env:
  AZURE_WEBAPP_NAME: technight-webapp    # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'         # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0'                  # set this to the .NET Core version to use

on:
  push:
    branches: [ "develop", "feature/gh-action-workflow" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build Web App
        run: dotnet build ./TechNight-WebApp -c Release

      - name: Publish Web App
        run: dotnet publish ./TechNight-WebApp -c Release -o ${{ env.DOTNET_ROOT }}/technight-webapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/technight-webapp