name: TechNight-WebApp-CICD

env:
  AZURE_WEBAPP_NAME: technight-webapp
  AZURE_WEBAPP_LOCATION: canadacentral
  AZURE_WEBAPP_RG: TN-RG

  AZURE_WEBAPP_PACKAGE_PATH: '.'         # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0'                  # set this to the .NET Core version to use

on:
  push:
    branches: [ "develop", "feature/gh-action-workflow" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build Web App
        run: dotnet build ./TechNight-WebApp -c Release

      - name: Publish Web App
        run: dotnet publish ./TechNight-WebApp -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/technight-webapp

      - name: Upload application's files for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/technight-webapp
          if-no-files-found: error

      - name: Upload Bicep template for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: arm-templates/webapp/azuredeploy.bicep
          if-no-files-found: error

  dev:
    permissions:
        contents: none
    runs-on: ubuntu-latest
    needs: build
    environment: 'DEVELOPMENT'

    env:
      envPrefix: DEV

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      id: download
      with:
        name: artifacts

    # Log into Azure
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Deploy Bicep file
    - name: Deploy Bicep Template (Web App Infra)
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTIONID }}
        resourceGroupName: 'DEV-${{env.AZURE_WEBAPP_RG}}'
        deploymentMode: 'Incremental'
        template: 'azuredeploy.bicep'
        parameters: > 
          envPrefix=${{ env.envPrefix }} 
          webAppName=${{ env.AZURE_WEBAPP_NAME }}
        failOnStdErr: false

    # Deploy to Azure Web apps
    - name: 'Deploy Web App'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.envPrefix }}-${{ env.AZURE_WEBAPP_NAME }}
        package: ${{steps.download.outputs.download-path}}

    - name: Log out of Azure
      run: az logout